name: build-push-and-redeploy
on:
  push:
    branches: ["main", "dev"]
    tags: ["v*.*.*"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NS: ${{ github.repository_owner }}/champion

jobs:
  build-backend:
    runs-on: ubuntu-latest
    #    Fix before releasing main branch
    #    environment: ${{ github.ref_name == 'main' && 'prod' || 'stage' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: docker/setup-buildx-action@v3
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta (backend)
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NS }}-backend
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=stage
            type=raw,value=prod
          #  Fix before releasing main branch
          #  type=raw,value=${{ github.ref_name == 'main' && 'prod' || 'stage' }}

      - name: Build+Push (backend)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}
          provenance: false
          sbom: false

  #  build-frontend:
  #    runs-on: ubuntu-latest
  #    environment: ${{ github.ref_name == 'main' && 'prod' || 'stage' }}
  #    steps:
  #      - uses: actions/checkout@v4
  #        with:
  #          fetch-depth: 1
  #      - uses: docker/setup-buildx-action@v3
  #      - name: Login GHCR
  #        uses: docker/login-action@v3
  #        with:
  #          registry: ${{ env.REGISTRY }}
  #          username: ${{ github.actor }}
  #          password: ${{ secrets.GITHUB_TOKEN }}
  #
  #      - name: Meta (frontend)
  #        id: meta_frontend
  #        uses: docker/metadata-action@v5
  #        with:
  #          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NS }}-frontend
  #          tags: |
  #            type=ref,event=branch
  #            type=ref,event=tag
  #            type=sha
  #            type=raw,value=latest,enable={{is_default_branch}}
  #            type=raw,value=${{ github.ref_name == 'main' && 'prod' || 'stage' }}
  #
  #      - name: Build+Push (frontend)
  #        uses: docker/build-push-action@v6
  #        with:
  #          context: ./frontend
  #          file: ./frontend/Dockerfile
  #          platforms: linux/amd64
  #          push: true
  #          tags: ${{ steps.meta_frontend.outputs.tags }}
  #          labels: ${{ steps.meta_frontend.outputs.labels }}
  #          build-args: |
  #            NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL }}
  #            NEXT_PUBLIC_CDN_URL=${{ vars.NEXT_PUBLIC_CDN_URL }}
  #            NEXT_PUBLIC_ANALYTICS_URL=${{ vars.NEXT_PUBLIC_ANALYTICS_URL }}
  #            NEXT_PUBLIC_ANALYTICS_ID=${{ vars.NEXT_PUBLIC_ANALYTICS_ID }}
  #          provenance: false
  #          sbom: false

  build-frontend-stage:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta (frontend stage)
        id: meta_frontend_stage
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NS }}-frontend
          tags: |
            type=raw,value=stage

      - name: Build+Push (frontend stage)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta_frontend_stage.outputs.tags }}
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL }}
            NEXT_PUBLIC_CDN_URL=${{ vars.NEXT_PUBLIC_CDN_URL }}
            NEXT_PUBLIC_ANALYTICS_URL=${{ vars.NEXT_PUBLIC_ANALYTICS_URL }}
            NEXT_PUBLIC_ANALYTICS_ID=${{ vars.NEXT_PUBLIC_ANALYTICS_ID }}

  build-frontend-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta (frontend prod)
        id: meta_frontend_prod
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NS }}-frontend
          tags: |
            type=raw,value=prod

      - name: Build+Push (frontend prod)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta_frontend_prod.outputs.tags }}
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL }}
            NEXT_PUBLIC_CDN_URL=${{ vars.NEXT_PUBLIC_CDN_URL }}
            NEXT_PUBLIC_ANALYTICS_URL=${{ vars.NEXT_PUBLIC_ANALYTICS_URL }}
            NEXT_PUBLIC_ANALYTICS_ID=${{ vars.NEXT_PUBLIC_ANALYTICS_ID }}

#  redeploy:
#    runs-on: ubuntu-latest
#    needs: [ build-backend, build-frontend ]
#    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
#    steps:
#      - name: Trigger Portainer stack webhook
#        run: curl -fsSL -X POST "${{ secrets.PORTAINER_STACK_WEBHOOK }}"

  redeploy-dev:
    runs-on: ubuntu-latest
    needs: [ build-backend, build-frontend-stage ]
    environment: dev
    steps:
      - name: Trigger Portainer stack webhook (dev)
        run: curl -fsSL -X POST "${{ secrets.PORTAINER_STACK_WEBHOOK }}"

  redeploy-prod:
    runs-on: ubuntu-latest
    needs: [ build-backend, build-frontend-prod ]
    environment: prod
    steps:
      - name: Trigger Portainer stack webhook (prod)
        run: curl -fsSL -X POST "${{ secrets.PORTAINER_STACK_WEBHOOK }}"